terraform-google-modules/terraform-example-foundation

.gitignore
0-bootstrap/README.md
0-bootstrap/backend.tf.example
0-bootstrap/main.tf
0-bootstrap/outputs.tf
0-bootstrap/terraform.example.tfvars
0-bootstrap/variables.tf
0-bootstrap/versions.tf
CODEOWNERS
CONTRIBUTING.md
Makefile
README.md
build/lint.cloudbuild.yaml

Adding the first part of the example foundation. I will submit each section as a separate PR to make it more digestible to review and document each individually.

feat: add bootstrap step

---

2-networks/README.md
2-networks/backend.tf
2-networks/cloudbuild-tf-apply.yaml
2-networks/cloudbuild-tf-plan.yaml
2-networks/main.tf
2-networks/modules/standard_shared_vpc/README.md
2-networks/modules/standard_shared_vpc/data.tf
2-networks/modules/standard_shared_vpc/main.tf
2-networks/modules/standard_shared_vpc/outputs.tf
2-networks/modules/standard_shared_vpc/variables.tf
2-networks/modules/standard_shared_vpc/versions.tf
2-networks/outputs.tf
2-networks/providers.tf
2-networks/variables.tf
2-networks/versions.tf

The purpose of this step is to setup shared VPCs with default DNS, NAT, Private Service networking and baseline firewall rules.

feat: Add initial networking code

---

0-bootstrap/README.md
1-org/README.md

Minor clarifications to 0-bootstrap and 1-org READMEs

Minor clarifications to 0-bootstrap and 1-org READMEs

---

2-networks/terraform.example.tfvars

fix: Add missing example tfvars file for networks, fixing #17

---

0-bootstrap/main.tf
2-environments/README.md

Creation of a new cloud repo  for step `2-environments`
- add the `gcp-environments` repo to the repos created in step `0-bootstrap` 
- update reference in `2-environments` README.md

create gcp-environments repo.

---

1-org/README.md
1-org/projects.tf
1-org/variables.tf

Hello folks!
This pull requests creates the interconnect host project.
Could you please, take a look?
Thanks!

Adds interconnect project

---

.gitignore
0-bootstrap/modules/jenkins/README.md
0-bootstrap/modules/jenkins/main.tf
0-bootstrap/modules/jenkins/outputs.tf
0-bootstrap/modules/jenkins/variables.tf

New PR with Jenkins Agent - Initial commit

Adding Jenkins Agent 01

---

3-networks/modules/dedicated_interconnect/README.md

Fix spelling in the dedicated interconnect README.md file

Fix dedicated interconnect README.md

---

3-networks/envs/dev/main.tf
3-networks/envs/nonprod/main.tf
3-networks/envs/prod/main.tf
3-networks/envs/shared/main.tf
3-networks/modules/dedicated_interconnect/main.tf
3-networks/modules/restricted_shared_vpc/dns.tf
3-networks/modules/standard_shared_vpc/dns.tf

Adding `lifecycleState=ACTIVE` to data "google_projects" to filter out deleted projects.

add lifecycleState ACTIVE to terraform projects data filter

---

0-bootstrap/main.tf

Changing bootstrap to support mono repo structure. 
FYI @mikelaramie

refactor: Changing cloud build configuration to mono-repo structure

---

1-org/envs/shared/README.md
1-org/envs/shared/log_sinks.tf
1-org/envs/shared/variables.tf

Changes in this PR:
- add logging sinks for: "VPC Flow Logs", "Firewall Rules Logging" and "Access Transparency logs".
- add "google_organization_iam_audit_config" or "google_folder_iam_audit_config" with toggle(default = true) for "allServices" with DATA_READ, DATA_WRITE and ADMIN_READ.
- update README with disclaimer regarding the cost of data access logs.
@bharathkkb @rjerrems @morgante Could you please take a look at this change?

add missing sinks and enable data access logs.

---

3-networks/envs/dev/README.md
3-networks/envs/dev/vpn.tf.example
3-networks/envs/nonprod/README.md
3-networks/envs/nonprod/vpn.tf.example
3-networks/envs/prod/README.md
3-networks/envs/prod/vpn.tf.example

Hi @rjerrems @bharathkkb and @morgante 
This pull request just adds a few improvements on the README about the HA VPN.
Can you, please, take a look? Thanks :)

Improves instructions for VPN usage

---

1-org/envs/shared/folders.tf
1-org/envs/shared/projects.tf
2-environments/modules/env_baseline/folders.tf
2-environments/modules/env_baseline/monitoring.tf
2-environments/modules/env_baseline/secrets.tf
3-networks/envs/shared/main.tf
3-networks/modules/dedicated_interconnect/main.tf
3-networks/modules/restricted_shared_vpc/dns.tf
3-networks/modules/standard_shared_vpc/dns.tf

Removed subfolders from 'common', updated some project names/labels and corresponding data references.

flatten folder structure and modify references

---

0-bootstrap/main.tf

Adds support for git and terraform-validator

refactor: upgrade bootstrap module version

---

0-bootstrap/modules/jenkins-agent/files/jenkins_gce_startup_script.sh

fix: align jenkins terraform-validator versions with cloudbuild bootstrap

---

.kitchen.yml
test/fixtures/bootstrap/outputs.tf
test/integration/bootstrap/controls/bootstrap.rb
test/integration/bootstrap/controls/cloudbuild.rb
test/integration/bootstrap/controls/gcloud_cloudbuild.rb
test/integration/bootstrap/controls/gcp_bootstrap.rb
test/integration/bootstrap/controls/gcp_cloudbuild.rb
test/integration/bootstrap/inspec.yml

This pull request adds integration tests for step 0-bootstrap, please take a look.

Adds integration test for step 0-bootstrap

---

4-projects/business_unit_1/dev/example_base_shared_vpc_project.tf
4-projects/business_unit_1/dev/example_floating_project.tf
4-projects/business_unit_1/dev/example_restricted_shared_vpc_project.tf
4-projects/business_unit_1/dev/variables.tf
4-projects/business_unit_1/nonprod/example_base_shared_vpc_project.tf
4-projects/business_unit_1/nonprod/example_floating_project.tf
4-projects/business_unit_1/nonprod/example_restricted_shared_vpc_project.tf
4-projects/business_unit_1/nonprod/variables.tf
4-projects/business_unit_1/prod/example_base_shared_vpc_project.tf
4-projects/business_unit_1/prod/example_floating_project.tf
4-projects/business_unit_1/prod/example_restricted_shared_vpc_project.tf
4-projects/business_unit_1/prod/variables.tf
4-projects/business_unit_2/dev/example_base_shared_vpc_project.tf
4-projects/business_unit_2/dev/example_floating_project.tf
4-projects/business_unit_2/dev/example_restricted_shared_vpc_project.tf
4-projects/business_unit_2/dev/variables.tf
4-projects/business_unit_2/nonprod/example_base_shared_vpc_project.tf
4-projects/business_unit_2/nonprod/example_floating_project.tf
4-projects/business_unit_2/nonprod/example_restricted_shared_vpc_project.tf
4-projects/business_unit_2/nonprod/variables.tf
4-projects/business_unit_2/prod/example_base_shared_vpc_project.tf
4-projects/business_unit_2/prod/example_floating_project.tf
4-projects/business_unit_2/prod/example_restricted_shared_vpc_project.tf
4-projects/business_unit_2/prod/variables.tf
4-projects/modules/single_project/README.md
4-projects/modules/single_project/data.tf
4-projects/modules/single_project/main.tf
4-projects/modules/single_project/variables.tf

After recreating all of projects in my test org, I found out that we were missing the prefix "prj"

fix: add missing prj prefixes

---

0-bootstrap/.gitignore
1-org/.gitignore
2-environments/.gitignore
3-networks/.gitignore
4-projects/.gitignore

Adding .gitignore files to step folders since they will be top level folders when they are copied to the cloud repos in the cloud build flow

add .gitignore files to step folders.

---

3-networks/modules/restricted_shared_vpc/service_control.tf

Replace module
`"terraform-google-modules/vpc-service-controls/google//modules/regular_service_perimeter"`
with native resource
`resource "google_access_context_manager_service_perimeter"`
to set lifecycle so that changes to status are ignored.
Closes #151

replace module with native resource to set lifecycle

---

4-projects/README.md
4-projects/business_unit_1/dev/common.auto.tfvars
4-projects/business_unit_1/dev/dev.auto.tfvars
4-projects/business_unit_1/nonprod/common.auto.tfvars
4-projects/business_unit_1/nonprod/nonprod.auto.tfvars
4-projects/business_unit_1/prod/common.auto.tfvars
4-projects/business_unit_1/prod/prod.auto.tfvars
4-projects/business_unit_2/dev/common.auto.tfvars
4-projects/business_unit_2/dev/dev.auto.tfvars
4-projects/business_unit_2/nonprod/common.auto.tfvars
4-projects/business_unit_2/nonprod/nonprod.auto.tfvars
4-projects/business_unit_2/prod/common.auto.tfvars
4-projects/business_unit_2/prod/prod.auto.tfvars
4-projects/common.auto.example.tfvars
4-projects/dev.auto.example.tfvars
4-projects/nonprod.auto.example.tfvars
4-projects/prod.auto.example.tfvars

Added a common tfvar file, three environment tfvar files and their symbolic links.
Also update README.md instructions regarding tfvar files and perimeter_name variable
Closes #130

add common.auto.tfvars and env.auto.tfvars to 4-projects

---

build/Jenkinsfile

fixes #147 
- Example run for `dev|prod|nonprod` branches
- Example run for any other branch

Add conditional stages for Jenkins

---

0-bootstrap/README.md

Adding a note about the project creation quota issue and how to request more quota using a form

add note about project creation quota error

---

4-projects/modules/single_project/data.tf

Adding to the projects filter used in 4-projects the parent.id filter

filter projects with parent.id in 4-projects

---

3-networks/envs/dev/main.tf
3-networks/envs/nonprod/main.tf
3-networks/envs/prod/main.tf

Part of the fixes from this PR https://github.com/terraform-google-modules/terraform-example-foundation/pull/139 where removed.
Fixes in dev/nonprod/prod:
- Disable NAT in private shared VPC
- Disable windows activation in private shared VPC

disable NAT and windows activation

---

3-networks/modules/restricted_shared_vpc/firewall.tf
3-networks/modules/standard_shared_vpc/firewall.tf

Add missing firewall tags to:
- windows activation
- allow google private api
- allow google restricted api

add missing tags to firewall rules.

---

README.md

Add docs around recommended branching strategies followed in the repo.

Add branching docs

---

0-bootstrap/main.tf

Addresses defects @daniel-cit surfaced when comparing to white paper

refactor: bootstrap change folder name & add labels

---

0-bootstrap/modules/jenkins-agent/main.tf
1-org/envs/shared/projects.tf
3-networks/envs/dev/main.tf
3-networks/envs/nonprod/main.tf
3-networks/envs/prod/main.tf
3-networks/envs/shared/main.tf
3-networks/modules/base_shared_vpc/dns.tf
3-networks/modules/base_shared_vpc/main.tf
3-networks/modules/dedicated_interconnect/README.md
3-networks/modules/dedicated_interconnect/main.tf
3-networks/modules/dedicated_interconnect/variables.tf
3-networks/modules/restricted_shared_vpc/dns.tf
3-networks/modules/restricted_shared_vpc/main.tf
test/integration/dns_hub/controls/gcloud_dns_hub.rb
test/integration/dns_hub/controls/gcp_dns_hub.rb

- jenkins subnetwork
- logging project
- env code in common project
- dns hub project, vpc and subnets
- cloud routers
- interconnect vlans

fix multiple naming issues

---

0-bootstrap/README.md
0-bootstrap/main.tf
0-bootstrap/modules/jenkins-agent/main.tf
0-bootstrap/variables.tf
1-org/envs/shared/README.md
1-org/envs/shared/projects.tf
1-org/envs/shared/variables.tf
2-environments/modules/env_baseline/README.md
2-environments/modules/env_baseline/monitoring.tf
2-environments/modules/env_baseline/networking.tf
2-environments/modules/env_baseline/secrets.tf
2-environments/modules/env_baseline/variables.tf
4-projects/modules/single_project/README.md
4-projects/modules/single_project/main.tf
4-projects/modules/single_project/variables.tf
test/setup/main.tf

Fixes #185 
- expose budget control vars
- set default values including budget_amount to 1000

Expose budget controls from project factory

---

0-bootstrap/README-Jenkins.md

Thank you @Daniel-cti for the help here.

Added instructions to use the SSH private key password

---

0-bootstrap/README.md
0-bootstrap/main.tf
0-bootstrap/variables.tf

Changes in this PR:
- Add `billing.admin` role to the Terraform Service Account
- Remove budget from projects in 0-bootstrap:
- seed
- cloud build
- Jenkins
Fixes #195 
Fixes #194

0-bootstrap budget fixes

---

1-org/envs/shared/terraform.example.tfvars

To help prevent customers running into this issue:
https://github.com/terraform-google-modules/terraform-example-foundation/issues/176

fix: add default value for scc notification, update region for consistency

---

test/integration/bootstrap/controls/gcloud_cloudbuild.rb

Fixes the test that checks the cloudbuild triggers creation (Issue #212  ).

Fixes 0-bootstrap kitchen tests

---

3-networks/envs/development/vpn.tf.example
3-networks/envs/non-production/vpn.tf.example
3-networks/envs/production/vpn.tf.example
3-networks/modules/vpn-ha/README.md
3-networks/modules/vpn-ha/main.tf
3-networks/modules/vpn-ha/variables.tf

Hey folks!
This pull request adds the parent for secret project filter in VPN module.
Can you take a look?
Thanks!

Adds parent on secret project filter

---

README.md

Added changes from https://github.com/terraform-google-modules/terraform-example-foundation/pull/216
+ some additional fixes.
Branched from master to avoid clashes.

fix: main README updates.

---

CONTRIBUTING.md

- update int test guide for contributors

Update CONTRIBUTING.md with testing

---

0-bootstrap/modules/jenkins-agent/main.tf
3-networks/modules/base_shared_vpc/firewall.tf
3-networks/modules/restricted_shared_vpc/firewall.tf

Hey folks! 
This pull request closes #221 issue!
Could you please, take a look?
Thanks!

Updates google_compute_firewall to use log_config

---

3-networks/README.md
3-networks/envs/development/README.md
3-networks/envs/development/main.tf
3-networks/envs/development/variables.tf
3-networks/envs/non-production/README.md
3-networks/envs/non-production/main.tf
3-networks/envs/non-production/variables.tf
3-networks/envs/production/README.md
3-networks/envs/production/main.tf
3-networks/envs/production/variables.tf

Hey Folks
This PR highlights the toggles for optional services on step 3-network.
Can you take a look? 
Thanks!

Adds optionals section on README for step 3-networks

---

1-org/envs/shared/iam.tf

This is required for HIPAA alignment.

actually enable data access logs collection

---

1-org/README.md
1-org/envs/shared/README.md
1-org/envs/shared/log_sinks.tf
1-org/envs/shared/variables.tf

Hey folks,
This pull request closes #256 issue.
Thanks!

Adds support to bucket retention policy

---

0-bootstrap/README.md
0-bootstrap/main.tf
0-bootstrap/variables.tf

Hey folks!
This pull request closes #254 issue.
Thanks!

Adds org policy admin role for admin group

---

build/tf-wrapper.sh

Add a `show` command to `tf-wrapper.sh`.
Closes #259

feat: add terraform show command to wrapper script

---

0-bootstrap/main.tf
0-bootstrap/modules/jenkins-agent/main.tf
1-org/envs/shared/README.md
1-org/envs/shared/log_sinks.tf
1-org/envs/shared/variables.tf
test/fixtures/org/main.tf

Hey folks!
This pull request closes #255 and #242 issues.
Thanks!
>> Dependes of https://github.com/terraform-google-modules/terraform-google-log-export/pull/64

Fixes deprecated bucket-policy-only parameter

---

1-org/README.md
1-org/envs/shared/README.md
1-org/envs/shared/log_sinks.tf
1-org/envs/shared/variables.tf
test/fixtures/org/main.tf
test/integration/org/controls/gcp_logging.rb

Hey folks
This pull request closes #258 issue.
Thanks!

Removes filter for sinks

---

0-bootstrap/README.md
0-bootstrap/modules/jenkins-agent/README.md
1-org/envs/shared/README.md
2-environments/envs/development/README.md
2-environments/envs/non-production/README.md
2-environments/envs/production/README.md
2-environments/modules/env_baseline/README.md
3-networks/envs/development/README.md
3-networks/envs/non-production/README.md
3-networks/envs/production/README.md
3-networks/envs/shared/README.md
3-networks/modules/base_shared_vpc/README.md
3-networks/modules/dedicated_interconnect/README.md
3-networks/modules/restricted_shared_vpc/README.md
3-networks/modules/vpn-ha/README.md
4-projects/business_unit_1/development/README.md
4-projects/business_unit_1/non-production/README.md
4-projects/business_unit_1/production/README.md
4-projects/business_unit_2/development/README.md
4-projects/business_unit_2/non-production/README.md
4-projects/business_unit_2/production/README.md
4-projects/modules/single_project/README.md
Makefile
build/lint.cloudbuild.yaml
test/bundle.hcl

Local tests:
- time to validate without bundle: `25m`. dir size: `5.2GB`
- time to validate with bundle: `11m`. dir size: `400MB`
- time to validate with bundle and parallel: `5m`. dir size: `400MB`
Cloud build:
- time to validate without bundle: ~ `7m`
- time to validate with bundle and parallel: `2m`
ref: https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/pull/773

feat: Add Provider cache

---

.kitchen.yml
0-bootstrap/main.tf
0-bootstrap/modules/jenkins-agent/main.tf
0-bootstrap/modules/jenkins-agent/versions.tf
0-bootstrap/versions.tf
1-org/envs/shared/projects.tf
2-environments/modules/env_baseline/monitoring.tf
2-environments/modules/env_baseline/networking.tf
2-environments/modules/env_baseline/secrets.tf
3-networks/envs/shared/main.tf
3-networks/modules/base_shared_vpc/main.tf
3-networks/modules/dedicated_interconnect/main.tf
3-networks/modules/restricted_shared_vpc/main.tf
4-projects/modules/single_project/main.tf
Makefile
build/int.cloudbuild.yaml
build/lint.cloudbuild.yaml
test/integration/projects/controls/gcloud_projects.rb
test/setup/main.tf

fixes #238 #226
- Bumped versions across modules where necessary for TF0.13 compat
- Updated CI images
Todo:

feat: Updates for TF 0.13

---

.github/release-please.yml

- Adds release-please config for auto changelog generation and release management

chore: Add release-please config

---

1-org/envs/shared/log_sinks.tf

feat: Make BigQuery log destinations to be partitioned

---

1-org/envs/shared/projects.tf
2-environments/modules/env_baseline/secrets.tf

fix: Set default_service_account value as 'deprivilege'

---

0-bootstrap/README.md

doc: 0-bootstrap, add 'Organization Not Found' related actions

---

1-org/README.md
1-org/envs/shared/README.md
1-org/envs/shared/org_policy.tf
1-org/envs/shared/variables.tf
test/fixtures/org/main.tf
test/integration/org/controls/gcloud_policy.rb

This PR adds two new org policies:
- OS login 
- Shielded VMs
with a toggle for each one

New org policies

---

0-bootstrap/README.md
2-environments/README.md

This PR adds note on possible exceeded billing quota (I've experienced it myself) to document this issue before troubleshooting guide will be in place.
Closes #269

doc: Add note on billing quota exceeded

---

0-bootstrap/README.md
0-bootstrap/main.tf
0-bootstrap/variables.tf

Move SCR definition to variables.

Move SCR definition to variables.

---

4-projects/business_unit_1/development/providers.tf
4-projects/business_unit_1/non-production/providers.tf
4-projects/business_unit_1/production/providers.tf
4-projects/business_unit_2/development/providers.tf
4-projects/business_unit_2/non-production/providers.tf
4-projects/business_unit_2/production/providers.tf
build/int.cloudbuild.yaml
test/bundle.hcl
test/setup/outputs.tf
test/setup/variables.tf

- enables tests for each example-foundations mode
x-ref: https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/pull/852

feat: example-foundations test modes

---

0-bootstrap/README.md
0-bootstrap/variables.tf
1-org/README.md
2-environments/README.md
3-networks/README.md
4-projects/README.md
README.md

This PR fixes a couple of typos and updates all READMEs to ensure paragraphs consistently end with a period.

Documentation fixes

---

.gitignore
0-bootstrap/main.tf

- Update bootstrap module to v2.1
- Add terraform.tfvars to gitignore

Upgrade bootstrap module to v2.1

---

1-org/envs/shared/org_policy.tf
test/integration/org/controls/gcloud_policy.rb

Add constraint/iam.automaticIamGrantsForDefaultServiceAccounts to list of constraints in the org policy

Add iam.automaticIamGrantsForDefaultServiceAccounts constraint

---

0-bootstrap/README.md
0-bootstrap/main.tf
0-bootstrap/variables.tf
test/fixtures/bootstrap/main.tf
test/fixtures/bootstrap/variables.tf

- Update `project_id` and `state_bucket_name` in cloudbuild and seed module examples to follow whitepaper standards
- Update documentation
- Update tests to avoid build conflicts

update bootstrap example

---

3-networks/envs/development/providers.tf
3-networks/envs/non-production/providers.tf
3-networks/envs/production/providers.tf
3-networks/envs/shared/providers.tf

Fixes https://github.com/terraform-google-modules/terraform-example-foundation/issues/429

set 3-networks service account token lifetime to 1200s

---

1-org/README.md

Added orientation table at the top.
Pulled commands out of instruction sentences.
Need a Purpose statement.

Converted 1-org readme to new format.

---

0-bootstrap/README.md
0-bootstrap/terraform.example.tfvars
0-bootstrap/variables.tf

Fixes https://github.com/terraform-google-modules/terraform-example-foundation/issues/439

Fix 0-bootstrap uat feedback issues

---

1-org/README.md
1-org/envs/shared/README.md
1-org/envs/shared/terraform.example.tfvars
1-org/envs/shared/variables.tf

Fixes https://github.com/terraform-google-modules/terraform-example-foundation/issues/440

Fix 1-org uat feedback issues

---

2-environments/README.md
2-environments/envs/development/README.md
2-environments/envs/development/variables.tf
2-environments/envs/non-production/README.md
2-environments/envs/non-production/variables.tf
2-environments/envs/production/README.md
2-environments/envs/production/variables.tf
2-environments/terraform.example.tfvars

Fixes https://github.com/terraform-google-modules/terraform-example-foundation/issues/441

Fix 2-environment uat feedback issues

---

3-networks/README.md
3-networks/common.auto.example.tfvars
3-networks/envs/development/README.md
3-networks/envs/development/variables.tf
3-networks/envs/non-production/README.md
3-networks/envs/non-production/variables.tf
3-networks/envs/production/README.md
3-networks/envs/production/variables.tf
3-networks/envs/shared/README.md
3-networks/envs/shared/variables.tf
3-networks/shared.auto.example.tfvars

This pull request fixes part of the issue from https://github.com/terraform-google-modules/terraform-example-foundation/issues/442
A fix for missing roles for the org-terraform service account will be part of  another PR.

Fix 3-networks uat issues

---

4-projects/business_unit_1/shared/example_infra_pipeline.tf
4-projects/business_unit_2/shared/example_infra_pipeline.tf
4-projects/modules/infra_pipelines/README.md
4-projects/modules/infra_pipelines/main.tf
4-projects/modules/infra_pipelines/variables.tf

Fixes https://github.com/terraform-google-modules/terraform-example-foundation/issues/452

add impersonate to gcloud builds submit command in infra-pipeline module

---

4-projects/README.md
4-projects/business_unit_1/development/README.md
4-projects/business_unit_1/development/variables.tf
4-projects/business_unit_1/non-production/README.md
4-projects/business_unit_1/non-production/variables.tf
4-projects/business_unit_1/production/README.md
4-projects/business_unit_1/production/variables.tf
4-projects/business_unit_1/shared/README.md
4-projects/business_unit_1/shared/variables.tf
4-projects/common.auto.example.tfvars
4-projects/development.auto.example.tfvars
4-projects/non-production.auto.example.tfvars
4-projects/production.auto.example.tfvars

Fixes https://github.com/terraform-google-modules/terraform-example-foundation/issues/444

fix 4-projects uat feedback issues

---

5-app-infra/README.md
5-app-infra/bu1-development.auto.example.tfvars
5-app-infra/bu1-non-production.auto.example.tfvars
5-app-infra/bu1-production.auto.example.tfvars
5-app-infra/business_unit_1/development/README.md
5-app-infra/business_unit_1/development/variables.tf
5-app-infra/business_unit_1/non-production/README.md
5-app-infra/business_unit_1/non-production/variables.tf
5-app-infra/business_unit_1/production/README.md
5-app-infra/business_unit_1/production/variables.tf
5-app-infra/common.auto.example.tfvars

Fixes https://github.com/terraform-google-modules/terraform-example-foundation/issues/445

fix 5-app-infra uat feedback issues

---

0-bootstrap/README.md
1-org/README.md
2-environments/README.md
3-networks/README.md
4-projects/README.md
5-app-infra/README.md
README.md

Setting Cloud build as the initial option for the deploy instructions.

Set Cloud build as first deploy instructions

---

4-projects/README.md
4-projects/shared.auto.example.tfvars

Fixes https://github.com/terraform-google-modules/terraform-example-foundation/issues/389
Fixes https://github.com/terraform-google-modules/terraform-example-foundation/issues/443

Fix 4 projects jenkins instructions

---

0-bootstrap/README.md
1-org/README.md
2-environments/README.md
3-networks/README.md
4-projects/README.md
5-app-infra/README.md
docs/FAQ.md
docs/GLOSSARY.md
docs/TROUBLESHOOTING.md

The initial version of the `docs` folder with templates for the files:
- FAQ.md
- GLOSSARY.md
- TROUBLESHOOTING.md

initial version of docs folder and files

---

0-bootstrap/README.md

Fix command to execute terraform-validator

---

0-bootstrap/README.md
1-org/README.md
2-environments/README.md
3-networks/README.md
4-projects/README.md
5-app-infra/README.md

chore: fixes for issue 489

---

4-projects/README.md

remove duplicate line

---

.github/dependabot.yml
0-bootstrap/modules/jenkins-agent/versions.tf

Trying dependabot to keep repo insync with upstream module changes
fixes #508 
Example: https://github.com/bharathkkb/terraform-example-foundation/pulls

chore: Dependabot for upstream TF modules

---

5-app-infra/README.md

Remove duplicate line and add impersonation step for running terraform manually

Remove duplicate line and add impersonation

---

0-bootstrap/main.tf

fix: Issue #628 Failed Cloud Build plan in 1-org using cloud build SA from TFV

---

Makefile
build/int.cloudbuild.yaml
build/lint.cloudbuild.yaml

bump developer tools image version to 1.5

chore: bump developer tools image version to 1.5

---

0-bootstrap/README.md

Fixed Google Cloud SDK version that supports gcloud terraform vet

---

0-bootstrap/README.md

added missing Organization Policy Admin role for bootstrap step

---

README.md

main README fixes

---

CONTRIBUTING.md
Makefile

Update instructions in CONTRIBUTING.md and fix environment variables required for:
- `make docker_test_prepare`
- `make docker_test_cleanup`
- `make docker_run`

update CONTRIBUTING.md and Makefile

---

5-app-infra/README.md

Suggestion to improve gcp-policies clone command

Suggestion to improve gcp-policies clone command on README

---

0-bootstrap/README.md
1-org/README.md
1-org/envs/shared/README.md
1-org/envs/shared/main.tf
1-org/envs/shared/projects.tf
1-org/envs/shared/terraform.example.tfvars
1-org/envs/shared/variables.tf
2-environments/README.md
2-environments/terraform.example.tfvars
3-networks-dual-svpc/README.md
3-networks-dual-svpc/access_context.auto.example.tfvars
3-networks-dual-svpc/common.auto.example.tfvars
3-networks-hub-and-spoke/README.md
3-networks-hub-and-spoke/access_context.auto.example.tfvars
3-networks-hub-and-spoke/common.auto.example.tfvars
4-projects/README.md
4-projects/business_unit_1/shared/README.md
4-projects/business_unit_1/shared/example_infra_pipeline.tf
4-projects/business_unit_1/shared/main.tf
4-projects/business_unit_1/shared/variables.tf
4-projects/business_unit_2/shared/README.md
4-projects/business_unit_2/shared/example_infra_pipeline.tf
4-projects/business_unit_2/shared/main.tf
4-projects/business_unit_2/shared/variables.tf
4-projects/common.auto.example.tfvars
4-projects/shared.auto.example.tfvars
5-app-infra/README.md
test/integration/org/org_test.go
test/integration/projects-shared/projects_shared_test.go

Update manual instructions to deploy the Example Foundation

Update manual instructions to deploy the Example Foundation

---

3-networks-dual-svpc/shared.auto.example.tfvars
3-networks-hub-and-spoke/shared.auto.example.tfvars
4-projects/business_unit_1/shared/README.md
4-projects/business_unit_1/shared/example_infra_pipeline.tf
4-projects/business_unit_1/shared/outputs.tf
4-projects/business_unit_2/shared/README.md
4-projects/business_unit_2/shared/example_infra_pipeline.tf
4-projects/business_unit_2/shared/outputs.tf
4-projects/modules/base_env/example_base_shared_vpc_project.tf
4-projects/modules/base_env/main.tf

Inline 4-projects shared App Infra Pipeline `sa_roles` in to the example base shared vpc project creation

Inline App Infra Pipeline `sa_roles`

---

3-networks-dual-svpc/modules/base_shared_vpc/firewall.tf
3-networks-dual-svpc/modules/restricted_shared_vpc/firewall.tf
3-networks-hub-and-spoke/modules/base_shared_vpc/firewall.tf
3-networks-hub-and-spoke/modules/restricted_shared_vpc/firewall.tf
4-projects/modules/base_env/example_peering_project.tf
test/integration/networks/networks_test.go

Fix firewall policies to use priority `65530`

fix firewall priorities to use `65530`

---

0-bootstrap/modules/jenkins-agent/main.tf

add vpc flow logs configuration for Jenkins subnet in 0-bootstrap

add vpc flow logs configuration for jenkins subnet

---

0-bootstrap/README-Jenkins.md
0-bootstrap/modules/jenkins-agent/README.md
1-org/envs/shared/main.tf
1-org/envs/shared/org_policy.tf
build/Jenkinsfile

Fixes in Jenkins README and Jenkinsfile

Fixes for Jenkins CI/CD

---

0-bootstrap/README-Jenkins.md

update link to Jenkins agent module README file

chore: update link to Jenkins agent module README file

---

0-bootstrap/cb.tf

set random suffix of the CI/CD project to the same size of other project suffixes

chore: set random suffix to the same size of other project suffix

---

docs/TROUBLESHOOTING.md

add troubleshoot entry for error adding network peering when using the Hub and Spoke network mode

add troubleshoot entry for error adding network peering

---

0-bootstrap/modules/cb-private-pool/main.tf
0-bootstrap/modules/cb-private-pool/network.tf
0-bootstrap/sa.tf
3-networks-dual-svpc/modules/base_shared_vpc/firewall.tf
3-networks-dual-svpc/modules/restricted_shared_vpc/firewall.tf
3-networks-hub-and-spoke/modules/base_shared_vpc/firewall.tf
3-networks-hub-and-spoke/modules/restricted_shared_vpc/firewall.tf
3-networks-hub-and-spoke/modules/transitivity/main.tf
test/integration/bootstrap/bootstrap_test.go

update resource names to comply with naming convention

chore: comply with naming convention

---

0-bootstrap/cb.tf
0-bootstrap/modules/cb-private-pool/main.tf
0-bootstrap/modules/cb-private-pool/network.tf
0-bootstrap/modules/jenkins-agent/README.md
0-bootstrap/modules/jenkins-agent/main.tf
0-bootstrap/modules/jenkins-agent/variables.tf
0-bootstrap/sa.tf
4-projects/modules/base_env/example_peering_project.tf
test/integration/bootstrap/bootstrap_test.go

Enable missing DNS logging:
- Jenkins network
- Cloud Build peering network
- 4-projects peering example

enable missing DNS logging

---

3-networks-hub-and-spoke/modules/transitivity/main.tf
5-app-infra/modules/env_base/main.tf

block project-wide SSH keys

---

1-org/README.md

add note about object versioning and mutually exclusive relationship with bucket policy retention

add note about object versioning and mutually exclusive relationship with bucket policy retention

---

0-bootstrap/modules/parent-iam-remove-role/main.tf
0-bootstrap/modules/parent-iam-remove-role/variables.tf
0-bootstrap/modules/parent-iam-remove-role/versions.tf
0-bootstrap/sa.tf

remove Editor role  from Seed and CICD projects in 0-bootrstrap

remove Editor from Seed and CICD projects

---

docs/change_resource_hierarchy.md

Improved instructions to change `tf-wrapper.sh`

Improvements in resource hierarchy change document

---

3-networks-dual-svpc/modules/base_env/main.tf

fix: remove locals related to hub and spoke from dual shared vpc code

---

3-networks-hub-and-spoke/README.md

add note about updating transitivity firewall rules in the Hub and Spoke network mode

fix: add note about updating transitivity firewall rules in the Hub and Spoke network mode

---

.github/trusted-contribution.yml

@bharathkkb - We can use with https://github.com/googleapis/repo-automation-bots/tree/main/packages/trusted-contribution

chore: add trusted-contribution.yml

---

0-bootstrap/README.md

edited 0-bootstrap/README.md for v3 updates

chore(docs): Update README.md

---

1-org/README.md

Updating this readme for the v3 release.

Update 1-org readme

---

0-bootstrap/cb.tf

adds var.default_region as the location of the cloud build bucket

fix: add cloud build bucket location

---

0-bootstrap/README.md
0-bootstrap/onprem.md
0-bootstrap/variables.tf
README.md
docs/GLOSSARY.md

A few small changes and typo fixes in README and GLOSSARY files to make them easier to read.

chore(docs): Small edits in README files and GLOSSARY to clarify concepts

---

1-org/envs/shared/providers.tf

- bump `request_timeout` for 1-org
Fixes: #1069

fix(CI): bump request_timeout for 1-org

---

ERRATA.md
docs/GLOSSARY.md
docs/upgrading_to_v4.0.md

This PR updates the documentation related to the release 4.0

chore: Update release 4.0 docs

---

1-org/envs/shared/terraform.example.tfvars

Remove unused tfvars that were removed in this commit: https://github.com/terraform-google-modules/terraform-example-foundation/commit/f57a47c2e36e9924a3232983385e741fd05ee2f3#diff-772cebf2058d9fd66a2fd923eb13802b5a561daff7c66d1950d19675a3aa93f1

chore: remove unused tfvars

---

0-bootstrap/README-GitHub.md
0-bootstrap/README-GitLab.md
0-bootstrap/gitlab.tf.example

This PR update steps for deploy Github and Gitlab

Fix: Update Gitlab and GitHub steps
