terraform-google-modules/terraform-example-foundation

- 1-org/README.md
- 1-org/iam.tf
- 1-org/log_sinks.tf
- 1-org/terraform.example.tfvars
- 1-org/variables.tf
Separate out the IAM resources for clarity, and add a IAM Member with `roles/monitoring.editor` to the Monitoring Projects
> 1-org Separate IAM resources and add monitoring workspace permissions

- 2-environments/envs/dev/providers.tf
- 2-environments/envs/nonprod/providers.tf
- 2-environments/envs/prod/providers.tf
Projects created in step `2-environment`  do not have the Terraform service account created  in step `0-bootstrap` as the owner of the project. 
The owner of the project created is the user running Terraform. 
Step `2-environment` is missing the  `providers.tf` that enable the impersonation using the terraform service account created  in step `0-bootstrap`.
@rjerrems @morgante  @bharathkkb  could you please take a look at this fix?
> Add missing provider configuration to allow impersonation.

- 1-org/README.md
- 2-environments/README.md
- 3-networks/README.md
- 4-projects/README.md
Made changes to example-foundation READMEs based on run-through of example-foundation. 
Summary of Changes to READMEs:
1-org:
- added info about security admins GSuite group (prerequisite)
- added info about valid BQ dataset regions
2-environments:
- added README.md
- added instructions customized for envs/ folders (instructions for backend.tf, tfvars files)
- added info about creating monitoring admins groups (prerequisites)
- added info about creating new gcp-envs CSR repo & triggers replicated from gcp-org repo (prerequisites)
- added info about altering Cloud Build files to apply each environment folder
3-networks:
- small changes; replaced "2-networks" with "3-networks" in README
4-projects:
- small changes; replaced "3-projects" with "4-projects" in README
> Kellydodson: example-foundation readme updates

- .gitignore
- 3-networks/envs/dev/main.tf
- 3-networks/envs/nonprod/main.tf
- 3-networks/envs/prod/main.tf
- 3-networks/modules/dedicated_interconnect/README.md
- 3-networks/modules/dedicated_interconnect/main.tf
- 3-networks/modules/dedicated_interconnect/outputs.tf
- 3-networks/modules/dedicated_interconnect/variables.tf
Creation of  dedicated interconnect module in `3-networks`.
TODOs:
Depends on:
- https://github.com/terraform-google-modules/terraform-example-foundation/pull/72
- https://github.com/terraform-google-modules/terraform-example-foundation/pull/71
> Create dedicated interconnect module.

- 1-org/README.md
- 1-org/org_policy.tf
- 1-org/variables.tf
- build/int.cloudbuild.yaml
- test/fixtures/org/main.tf
Enables concurrent builds for int tests by
- randomize scc notif name
- pin `access_context_manager_access_policy` to use existing policy
> fix: Fix concurrent builds for int tests

- 3-networks/envs/dev/README.md
- 3-networks/envs/dev/main.tf
- 3-networks/envs/dev/variables.tf
- 3-networks/envs/nonprod/README.md
- 3-networks/envs/nonprod/main.tf
- 3-networks/envs/nonprod/variables.tf
- 3-networks/envs/prod/README.md
- 3-networks/envs/prod/main.tf
- 3-networks/envs/prod/variables.tf
- 3-networks/envs/shared/README.md
- 3-networks/envs/shared/main.tf
- 3-networks/envs/shared/variables.tf
- 3-networks/modules/restricted_shared_vpc/README.md
- 3-networks/modules/restricted_shared_vpc/firewall.tf
- 3-networks/modules/restricted_shared_vpc/variables.tf
- 3-networks/modules/standard_shared_vpc/README.md
- 3-networks/modules/standard_shared_vpc/firewall.tf
- 3-networks/modules/standard_shared_vpc/variables.tf
Changes in this pull request to support enabling network logs:
- DNS logs
- add dns_enable_logging to variables of 3-network/envs/[dev, nonprod, prod, shared]. Default value is "true" 
- Subnetwork Flow Logs
- add subnetworks_enable_logging to variables of 3-network/envs/[dev, nonprod, prod, shared]. Default value is "true" 
- use variable subnetworks_enable_logging in subnetworks definitions
- Firewall logs
- add firewall_enable_logging to variables of 3-network/envs/[dev,nonprod,prod]. Default value is "true"  
- add firewall_enable_logging to variables of 3-network/modules/[restricted_shared_vpc, standard_shared_vpc]. Default value is "true"  
- add variable firewall_enable_logging in firewall definitions
@morgante @rjerrems @bharathkkb  could you please take a look at this?
> Add flags to enable network logs.

- 0-bootstrap/README.md
- 0-bootstrap/main.tf
- 0-bootstrap/modules/jenkins-agent/README.md
- 0-bootstrap/modules/jenkins-agent/files/jenkins_gce_startup_script.sh
- 0-bootstrap/modules/jenkins-agent/main.tf
- 0-bootstrap/modules/jenkins-agent/variables.tf
- 0-bootstrap/outputs.tf
- 0-bootstrap/variables.tf
- README.md
@rjerrems and @bharathkkb 
This should be the last PR for the Jenkins Agent module.
- Successfully tested multiple times deploying the 0-bootstrap module using the jenkins module
- After configuring VPN manually between on-prem and CICD project, jobs run from on-prem into the CICD Jenkins Agent
> Adds a commented call to the jenkins-agent submodule

- 0-bootstrap/main.tf
Fixes `Error: no suitable version is available`  in  0-bootstrap step
```
No provider "google" plugins meet the constraint " < 4.0, < 4.0, < 4.0, < 4.0, < 4.0, < 4.0,>= 2.1,>= 2.1,>= 2.1,>= 2.1,>= 3.8,>= 3.8,~> 3.30.0,~> 3.31,~> 3.5".
```
@rjerrems @morgante @bharathkkb  could you please check this fix?
> Fix google provider version in 0-bootstrap step

- 1-org/envs/shared/iam.tf
Adding Billing Account Viewer to billing-data-users group at organization level so that user in this group can see billing info in the Cloud Console.
> Adding billing account viewer to billing-data-users group

- 1-org/envs/shared/README.md
- 2-environments/README.md
- 2-environments/envs/dev/terraform.tfvars
- 3-networks/README.md
- 3-networks/envs/dev/README.md
- 3-networks/envs/dev/variables.tf
- 3-networks/envs/nonprod/README.md
- 3-networks/envs/nonprod/variables.tf
- 3-networks/envs/prod/README.md
- 3-networks/envs/prod/variables.tf
- 3-networks/envs/shared/README.md
- 3-networks/modules/restricted_shared_vpc/README.md
- 3-networks/modules/restricted_shared_vpc/variables.tf
- 4-projects/README.md
- test/fixtures/networks/variables.tf
This PR fixes READMEs for all the steps for the execution of the Cloud Build deploy path with the new wrapper script.
It was also added the creation of a missing symbolic link in `2-environments/envs/dev` needed by the instructions. Fixes #110 
Depends on the script and cloud build files from PR https://github.com/terraform-google-modules/terraform-example-foundation/pull/100 and should be merged after PR #100 
@bharathkkb @rjerrems @mikelaramie @morgante Cloud you please take a look at these changes ?
> Fix readmes for cloud build with wrapper script and add missing symbolic link

- 4-projects/business_unit_1/dev/example_base_shared_vpc_project.tf
- 4-projects/business_unit_1/dev/example_restricted_shared_vpc_project.tf
- 4-projects/business_unit_1/dev/example_single_project.tf
- 4-projects/business_unit_1/dev/example_single_project_optional.tf
- 4-projects/business_unit_1/nonprod/example_base_shared_vpc_project.tf
- 4-projects/business_unit_1/nonprod/example_restricted_shared_vpc_project.tf
- 4-projects/business_unit_1/nonprod/example_single_project.tf
- 4-projects/business_unit_1/nonprod/example_single_project_optional.tf
- 4-projects/business_unit_1/prod/example_base_shared_vpc_project.tf
- 4-projects/business_unit_1/prod/example_restricted_shared_vpc_project.tf
- 4-projects/business_unit_1/prod/example_single_project.tf
- 4-projects/business_unit_1/prod/example_single_project_optional.tf
- 4-projects/business_unit_2/dev/example_base_shared_vpc_project.tf
- 4-projects/business_unit_2/dev/example_restricted_shared_vpc_project.tf
- 4-projects/business_unit_2/dev/example_single_project.tf
- 4-projects/business_unit_2/dev/example_single_project_optional.tf
- 4-projects/business_unit_2/dev/variables.tf
- 4-projects/business_unit_2/nonprod/example_base_shared_vpc_project.tf
- 4-projects/business_unit_2/nonprod/example_restricted_shared_vpc_project.tf
- 4-projects/business_unit_2/nonprod/example_single_project.tf
- 4-projects/business_unit_2/nonprod/example_single_project_optional.tf
- 4-projects/business_unit_2/nonprod/variables.tf
- 4-projects/business_unit_2/prod/example_base_shared_vpc_project.tf
- 4-projects/business_unit_2/prod/example_restricted_shared_vpc_project.tf
- 4-projects/business_unit_2/prod/example_single_project.tf
- 4-projects/business_unit_2/prod/example_single_project_optional.tf
- 4-projects/business_unit_2/prod/variables.tf
- test/export_sc.sh
- test/fixtures/projects/main.tf
fixes #119 
- Hardcodes application names across all envs
- bu1  -> `bu1-sample-application1`
- bu2  -> `bu2-sample-application2`
- Hardcode `local.business_code`
- Remove unused locals
- Add bu2 to IT
- Remove debug echo statements from helper
> fix: Hardcode some project details, add bu2 to integration tests

- 3-networks/envs/shared/README.md
- 3-networks/envs/shared/main.tf
- 3-networks/envs/shared/terraform.example.tfvars
- 3-networks/envs/shared/variables.tf
- test/fixtures/dns_hub/main.tf
DNS hub(env/shared) now uses the same variable names for the default_regions used by other envs (dev, nonprod, prod). 
Closes #136
Added the org_id to the terraform.example.tfvars.
Closes #125
> Dns hub fixes

- 3-networks/envs/dev/main.tf
- 3-networks/envs/nonprod/main.tf
- 3-networks/envs/prod/main.tf
- 3-networks/modules/restricted_shared_vpc/README.md
- 3-networks/modules/restricted_shared_vpc/variables.tf
- 3-networks/modules/standard_shared_vpc/README.md
- 3-networks/modules/standard_shared_vpc/firewall.tf
- 3-networks/modules/standard_shared_vpc/variables.tf
Makes default value and name for `default/optional` firewall rule enabled consistent.
Also fixes typo in logging toggle.
Closes #135
> make default value and name for  firewall rule enabled consistent

- 4-projects/README.md
- 4-projects/business_unit_1/dev/example_restricted_shared_vpc_project.tf
- 4-projects/business_unit_1/dev/variables.tf
- 4-projects/business_unit_1/nonprod/example_restricted_shared_vpc_project.tf
- 4-projects/business_unit_1/nonprod/variables.tf
- 4-projects/business_unit_1/prod/example_restricted_shared_vpc_project.tf
- 4-projects/business_unit_1/prod/variables.tf
- 4-projects/business_unit_2/dev/example_restricted_shared_vpc_project.tf
- 4-projects/business_unit_2/dev/variables.tf
- 4-projects/business_unit_2/nonprod/example_restricted_shared_vpc_project.tf
- 4-projects/business_unit_2/nonprod/variables.tf
- 4-projects/business_unit_2/prod/example_restricted_shared_vpc_project.tf
- 4-projects/business_unit_2/prod/variables.tf
- 4-projects/terraform.example.tfvars
- 4-projects/variables.tf
- test/fixtures/projects/main.tf
- test/fixtures/projects/variables.tf
This change makes access context manager policy id usage consistent between 3-networks and 4-projects.
> make access context manager policy id usage consistent

- 1-org/README.md
- 2-environments/README.md
- 3-networks/README.md
- 4-projects/README.md
Add instructions in the main README.md file of each step to copy the `.gitignore` file to the cloud repos of each step in the Cloud Build flow.
Closes #124 (the .gitignore item)
> copy .gitignore file to steps

- 3-networks/README.md
- 3-networks/shared.auto.example.tfvars
- test/fixtures/dns_hub/main.tf
This PR updates the values fro the examples for the target name servers used in the DNS forwarding zone of the DNS Hub
> update target name servers ip examples

- 1-org/envs/shared/projects.tf
- 2-environments/modules/env_baseline/monitoring.tf
- 2-environments/modules/env_baseline/networking.tf
- 2-environments/modules/env_baseline/secrets.tf
adding standard project labels for 1-org and 2-environments projects:
- 1-org
- logging
- billing
- secrets
- interconnect
- scc
- dns hub  
- 2-environments
- secrets
- monitoring
- base shared vpc
- restricted shared vpc
Fixes #189
> add standard project labels for 1-org and 2-environments projects

- 0-bootstrap/README-Jenkins.md
- build/Jenkinsfile
fixes #186 
- adds an optional step where Jenkins is blocked and will wait for manual confirmation via UI before proceeding with `terraform apply`
- this behaviour is disabled by default unless uncommented in Jenkinsfile
> Add optional code for manual approval Jenkins pipeline

- 4-projects/business_unit_1/development/dev.auto.tfvars
- 4-projects/business_unit_1/development/development.auto.tfvars
- 4-projects/business_unit_1/non-production/non-production.auto.tfvars
- 4-projects/business_unit_1/non-production/nonprod.auto.tfvars
- 4-projects/business_unit_1/production/prod.auto.tfvars
- 4-projects/business_unit_1/production/production.auto.tfvars
- 4-projects/business_unit_2/development/dev.auto.tfvars
- 4-projects/business_unit_2/development/development.auto.tfvars
- 4-projects/business_unit_2/non-production/non-production.auto.tfvars
- 4-projects/business_unit_2/non-production/nonprod.auto.tfvars
- 4-projects/business_unit_2/production/prod.auto.tfvars
- 4-projects/business_unit_2/production/production.auto.tfvars
Fixes https://github.com/terraform-google-modules/terraform-example-foundation/issues/199
> fix: rename symlinks to new naming convention for environments

- 0-bootstrap/main.tf
- test/integration/bootstrap/controls/gcloud_cloudbuild.rb
Currently the branch `non-production` triggers both apply and plan for cloud build, this change fixes that behavior. More details on bug raised on bootstrap module https://github.com/terraform-google-modules/terraform-google-bootstrap/issues/52
> fix: branch so that regex still works for cloud build with new environment names

- 0-bootstrap/README.md
- 1-org/README.md
- 2-environments/README.md
- 3-networks/README.md
- 3-networks/envs/development/README.md
- 3-networks/envs/non-production/README.md
- 3-networks/envs/production/README.md
- 3-networks/envs/shared/README.md
- 4-projects/README.md
- README.md
Fixes for:
- typos
- `to setup` -> `to set up`
- project name
- remove extra heading
- add full path to tfvars file
> Fix typos, instruction order and project name

- build/int.cloudbuild.yaml
- build/lint.cloudbuild.yaml
- pin tools image to 0.12.0 to prevent CI breakage with tf 0.13
- we can revert this once most modules have the version constraints relaxed
> pin tools image to 0.12.0

- 1-org/envs/shared/scc_notification.tf
I was having issues where `gcloud` was using the wrong project_id.
> explicitely add project to scc pub/sub topic creation

- 1-org/envs/shared/README.md
- 1-org/envs/shared/org_policy.tf
- 1-org/envs/shared/variables.tf
- test/fixtures/org/main.tf
- test/integration/org/controls/gcloud_policy.rb
Remove shielded VM organization policy as it is no longer necessary
> fix: remove shielded VM org policy

- 0-bootstrap/main.tf
- test/integration/bootstrap/controls/gcloud_cloudbuild.rb
- test/integration/bootstrap/controls/gcp_cloudbuild.rb
As `0-bootstrap` is meant to be run only once manually, it may be worthwhile removing the repository.
Closes #293
> fix: Remove 'gcp-bootstrap' repository

- 3-networks/README.md
- 3-networks/envs/development/README.md
- 3-networks/envs/development/main.tf
- 3-networks/envs/development/variables.tf
- 3-networks/envs/non-production/README.md
- 3-networks/envs/non-production/main.tf
- 3-networks/envs/non-production/variables.tf
- 3-networks/envs/production/README.md
- 3-networks/envs/production/main.tf
- 3-networks/envs/production/variables.tf
This PR fixes `3-networks` minor inconsistencies, typos and copy-pastas.
Closes #294
> fix: '3-networks' minor inconsistencies and typos

- 1-org/envs/shared/README.md
- 1-org/envs/shared/log_sinks.tf
- 1-org/envs/shared/variables.tf
- README.md
As per original issue, the storage bucket created by the `storage_destination` module does not have object versioning enabled, which is generating a finding in SHA against the CIS Benchmark for GCP. This PR:
- Updates underlying `log-export` module version to [5.1.0](https://github.com/terraform-google-modules/terraform-google-log-export/releases/tag/v5.1.0) as GCS object versioning is supported starting this version.
- Adds a note on GCS object versioning in general `README`.
Closes #274
> feat: Add log export GCS bucket object versioning

- 3-networks/envs/shared/access_context.auto.tfvars
Add symbolic link from the shared env to the top level access_context.auto.tfvars. The instructions in 3-networks/README.md assume this link exists, and step 11 fails if you don't create it.
> Add missing link in shared env

- build/tf-wrapper.sh
Currently `tf_plan_validate_all` calls `tf_validate` multiple times, which means the policies repo getting cloned multiple times. This results in an error the second time the clone is attempted since the path already exists
With this PR, `tf-wrapper.sh` verifies the existence of `/workspace/.policies-cloned` before attempting to clone.
> Clone policies repo once

- 1-org/envs/shared/versions.tf
- 2-environments/envs/development/versions.tf
- 2-environments/envs/non-production/versions.tf
- 2-environments/envs/production/versions.tf
- 3-networks/envs/development/versions.tf
- 3-networks/envs/non-production/versions.tf
- 3-networks/envs/production/versions.tf
- 3-networks/envs/shared/versions.tf
- 4-projects/business_unit_1/development/versions.tf
- 4-projects/business_unit_1/non-production/versions.tf
- 4-projects/business_unit_1/production/versions.tf
- 4-projects/business_unit_2/development/versions.tf
- 4-projects/business_unit_2/non-production/versions.tf
- 4-projects/business_unit_2/production/versions.tf
This pull request Fixes https://github.com/terraform-google-modules/terraform-example-foundation/issues/359
`google-beta` provider was pointing to the wrong source in the `version.tf` files:
It was:
```
google-beta = {
source  = "hashicorp/google"
version = ">= 3.50"
}
```
but it must be:
```
google-beta = {
source  = "hashicorp/google-beta"
version = ">= 3.50"
}
```
> fix google-beta provider source info

- build/cloudbuild-tf-apply.yaml
- build/cloudbuild-tf-plan.yaml
Fixes https://github.com/terraform-google-modules/terraform-example-foundation/issues/366
This PR replaces `gcr.io/$PROJECT_ID/terraform` with `$_DEFAULT_REGION-docker.pkg.dev/$PROJECT_ID/prj-tf-runners/terraform` in the CloudBuild files.
Result with the fix:
```
Starting Step #0 - "setup"
Step #0 - "setup": Pulling image: us-east1-docker.pkg.dev/prj-cloudbuild-34b9/prj-tf-runners/terraform
Step #0 - "setup": Using default tag: latest
Step #0 - "setup": latest: Pulling from prj-cloudbuild-34b9/prj-tf-runners/terraform
Step #0 - "setup": 75f546e73d8b: Already exists
```
> Replace container registery with artifact registry in CloudBuild

- 0-bootstrap/main.tf
Enables cloud build API in the seed project, used for creating infra-cicd triggers
> fix: add cloudbuild api to seed proj

- 4-projects/business_unit_1/development/example_peering_project.tf
- 4-projects/business_unit_1/non-production/example_peering_project.tf
- 4-projects/business_unit_1/production/example_peering_project.tf
- 4-projects/business_unit_2/development/example_peering_project.tf
- 4-projects/business_unit_2/non-production/example_peering_project.tf
- 4-projects/business_unit_2/production/example_peering_project.tf
The release of `network-peering` 3 which rolled to `terraform` 0.13 broke current master:
```
Step #1 - "tf plan validate all": Warning: Provider source not supported in Terraform v0.12
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all":   on .terraform/modules/peering/modules/network-peering/versions.tf line 20, in terraform:
Step #1 - "tf plan validate all":   20:     google = {
Step #1 - "tf plan validate all":   21:       source  = "hashicorp/google"
Step #1 - "tf plan validate all":   22:       version = "<4.0,>= 2.12"
Step #1 - "tf plan validate all":   23:     }
Step #1 - "tf plan validate all": 
Step #1 - "tf plan validate all": A source was declared for provider google. Terraform v0.12 does not support
Step #1 - "tf plan validate all": the provider source …
```
> fix: Pin network-peering for terraform 0.12

- 0-bootstrap/main.tf
Fix for [issue 381](https://github.com/terraform-google-modules/terraform-example-foundation/issues/381) - _KMS API is missing in seed_.
Added KMS Api in _main.tf_ in 0-bootstrap.
> Enabling KMS API in step 0-bootstrap

- 4-projects/business_unit_1/development/example_peering_project.tf
- 4-projects/business_unit_1/non-production/example_peering_project.tf
- 4-projects/business_unit_1/production/example_peering_project.tf
- 4-projects/business_unit_2/development/example_peering_project.tf
- 4-projects/business_unit_2/non-production/example_peering_project.tf
- 4-projects/business_unit_2/production/example_peering_project.tf
Fix for [issue 313](https://github.com/terraform-google-modules/terraform-example-foundation/issues/313) - _Pin peering module version in networks_
Added version in _peering module_ for business unit 1 and 2 in _example_peering_project.tf_ .
> Fixing version of network_peering in step 4-projects

- 3-networks/envs/shared/hierarchical_firewall.tf
This PR replaces the **allow all  protocols and ports** from the `allow-iap-ssh-rdp` rule
https://github.com/terraform-google-modules/terraform-example-foundation/blob/825d047679ec78ebd3f5b0fe72f6462bc029e573/3-networks/envs/shared/hierarchical_firewall.tf#L65
with the [recommended ports](https://cloud.google.com/iap/docs/using-tcp-forwarding#create-firewall-rule)
```
ports = {
tcp = ["22", "3389"]
}
```
> add ports to IAP TCP forwarding rule

- 0-bootstrap/README-Jenkins.md
- 0-bootstrap/README.md
- 0-bootstrap/main.tf
- 0-bootstrap/modules/jenkins-agent/README.md
- 0-bootstrap/modules/jenkins-agent/variables.tf
- 3-networks/modules/base_shared_vpc/versions.tf
- 3-networks/modules/restricted_shared_vpc/versions.tf
- 4-projects/modules/infra_pipelines/cloudbuild_builder/cloudbuild.yaml
- test/bundle.hcl
This PR sets the `terraform` version to `0.13.6` in the code and and in the references in the READMEs.
> Use terraform 0.13.6 in build and readme

- build/int.cloudbuild.yaml
Replace project_prefix used in the integration tests.
Changed from `tst` to `t01`.
Collision of new projects with existing projects has become more frequent:
```
Error: error creating project tst-p-shared-restricted-4d2b (tst-p-shared-restricted): googleapi: Error 409: Requested entity already exists, alreadyExists. If you received a 403 error, make sure you have the `roles/resourcemanager.projectCreator` permission
on .terraform/modules/production.env.restricted_shared_vpc_host_project/modules/core_project_factory/main.tf line 65, in resource "google_project" "main":
65: resource "google_project" "main" {    
```
> Replace project_prefix used in the integration tests

- 0-bootstrap/README.md
- 0-bootstrap/main.tf
- 0-bootstrap/outputs.tf
- 0-bootstrap/variables.tf
- test/integration/bootstrap/controls/gcp_cloudbuild.rb
This PR replaces the Google source repo created by the bootstrap cloud build module `gcp-policies` by a standalone `gcp-policies` repo because this repo does not need to have  Cloud Build triggers configured for it.
> add standalone repo for terraform-validator policies

- 4-projects/README.md
- 4-projects/business_unit_1/development/example_base_shared_vpc_project.tf
- 4-projects/business_unit_1/non-production/example_base_shared_vpc_project.tf
- 4-projects/business_unit_1/production/example_base_shared_vpc_project.tf
- 4-projects/business_unit_1/shared/README.md
- 4-projects/business_unit_1/shared/example_infra_pipeline.tf
- 4-projects/business_unit_1/shared/outputs.tf
- 4-projects/business_unit_1/shared/shared.auto.tfvars
- 4-projects/business_unit_1/shared/variables.tf
- 4-projects/business_unit_2/development/example_base_shared_vpc_project.tf
- 4-projects/business_unit_2/non-production/example_base_shared_vpc_project.tf
- 4-projects/business_unit_2/production/example_base_shared_vpc_project.tf
- 4-projects/business_unit_2/shared/README.md
- 4-projects/business_unit_2/shared/example_infra_pipeline.tf
- 4-projects/business_unit_2/shared/outputs.tf
- 4-projects/business_unit_2/shared/shared.auto.tfvars
- 4-projects/business_unit_2/shared/variables.tf
- 4-projects/modules/infra_pipelines/README.md
- 4-projects/modules/infra_pipelines/cloudbuild_builder/cloudbuild.yaml
- 4-projects/modules/infra_pipelines/main.tf
- 4-projects/modules/infra_pipelines/outputs.tf
- 4-projects/modules/infra_pipelines/variables.tf
- 4-projects/modules/single_project/main.tf
- 4-projects/shared.auto.example.tfvars
- 5-app-infra/README.md
- test/fixtures/projects/main.tf
- test/fixtures/projects/outputs.tf
- test/fixtures/projects/variables.tf
- test/integration/projects/controls/gcloud_projects.rb
- test/integration/projects/inspec.yml
- Added fix for [issue 377](https://github.com/terraform-google-modules/terraform-example-foundation/issues/377)
- Added test for artifact register creation
- Tested with step-5
- Added additional API's to base projects 
- Added additional roles to base project service account.
> Adding GAR in infra pipelines and test for artifact register

- 0-bootstrap/README-Jenkins.md
- 0-bootstrap/modules/jenkins-agent/README.md
- 0-bootstrap/modules/jenkins-agent/main.tf
- 4-projects/business_unit_1/development/example_storage_cmek.tf
- 4-projects/business_unit_1/non-production/example_storage_cmek.tf
- 4-projects/business_unit_1/production/example_storage_cmek.tf
- 4-projects/business_unit_2/development/example_storage_cmek.tf
- 4-projects/business_unit_2/non-production/example_storage_cmek.tf
- 4-projects/business_unit_2/production/example_storage_cmek.tf
- README.md
This PR closes https://github.com/terraform-google-modules/terraform-example-foundation/issues/410 , https://github.com/terraform-google-modules/terraform-example-foundation/issues/411 ,  https://github.com/terraform-google-modules/terraform-example-foundation/issues/412 
Also this PR unifies the name of the CICD project in **Jenkins** and **Cloud Build** to be `prj-b-cicd`
> Fix CMEK project name and root readme project names

- 5-app-infra/business_unit_1/development/main.tf
- 5-app-infra/business_unit_1/non-production/main.tf
- 5-app-infra/business_unit_1/production/main.tf
- 5-app-infra/modules/env_base/README.md
- 5-app-infra/modules/env_base/main.tf
- 5-app-infra/modules/env_base/variables.tf
- test/integration/app-infra/controls/gcp_projects.rb
Fixes https://github.com/terraform-google-modules/terraform-example-foundation/issues/415
> use f1-micro as the machine type for the deploy in 5-app-infra step

- 3-networks/envs/shared/net-hubs-transitivity.tf
- 3-networks/modules/transitivity/main.tf
- test/fixtures/shared/main.tf
- test/fixtures/shared/variables.tf
- test/setup/outputs.tf
This PR Fixes some issues when enabling hub and spoke transitivity.
> Fix hub and spoke transitivity issues

- 0-bootstrap/main.tf
This adds the functionality to bootstrap so no longer required here https://github.com/terraform-google-modules/terraform-google-bootstrap/pull/102
> chore: remove random id as this is now generated in bootstrap module

- build/cloudbuild-tf-apply.yaml
> chore: bump cb apply timeout

- test/integration/projects/controls/gcloud_projects.rb
This PR adds the test for the editor role on the Cloud Build service account and also removes the indexing from both service account tests.  Rebased on main according to PR #394.
> fix: add infra pipeline CB SA role test

- 1-org/README.md
- 2-environments/README.md
- 3-networks/README.md
- 4-projects/README.md
- 5-app-infra/README.md
This PR pins the `terraform-validator` version in the instructions for manual deploy of the foundation to version `2021-03-22`.
> Pin the terraform-validator version in the instructions for manual deploy of the foundation

- 0-bootstrap/README.md
- 1-org/envs/shared/scc_notification.tf
- test/clean_org.sh
- test/integration/org/controls/gcloud_scc.rb
This PR:
- Update google cloud sdk min version to 319.0.0 (the same version of the docker image for developer-tools:0.13  )
- Use GA version of `gcloud scc notifications`
> Update google cloud sdk min version to 319.0.0 and use GA version of gcloud scc notifications

- 1-org/README.md
Added setting up Security Command Center to  1-org README.md Prerequisites to address  [453](https://github.com/terraform-google-modules/terraform-example-foundation/issues/453)
>  1-org README.md add setting up Security Command Center to Prerequisites

- 0-bootstrap/README.md
Update README.md to match Jenkins. Change from copy `terraform.example.tfvars` to rename to avoid creating multiple input variable definition files.
> Update README.md re: terraform.example.tfvars

- 3-networks/modules/base_shared_vpc/dns.tf
- 3-networks/modules/restricted_shared_vpc/dns.tf
- test/integration/networks/controls/gcp_networks.rb
This Pull Request adds a DNS zone for `pkg.dev` in the base and restricted networks to allow usage of Google Artifact Registry.
> add DNS zone for artifact registry

- 4-projects/modules/infra_pipelines/README.md
- 4-projects/modules/infra_pipelines/main.tf
- 4-projects/modules/infra_pipelines/variables.tf
Add an optional list of folders to which the Cloud build Service account created in step 4 will need browser role to load IAM policies for terraform validator.
> add browser role to cloud build sa for provided folders

- 1-org/README.md
In this PR,
- I added a note in the prerequisites of `1-org` to inform users that they should request for sufficient projects quota and linked it to the detailed explanation in `FAQ.md`.
The reason for doing so is because I personally did not read the `FAQ.md` document nor the troubleshooting guide (I wasn't aware of those documents until I searched the error codes I was receiving on Google Search) and just followed the instructions as-is. On a fresh Cloud Identity org, `1-org` is where I hit the projects quota.
Now, I understand there are several issues related to this even with a fix in https://github.com/terraform-google-modules/terraform-example-foundation/pull/290 although I'm not sure why that note is gone and there was no mention of any prerequisites to check if you have enough …
> chore: added link to FAQ in 1-org

- 0-bootstrap/modules/jenkins-agent/main.tf
- 1-org/envs/shared/projects.tf
- test/setup/main.tf
This PR updates `terraform-google-project-factory` pessimistic version constraint to `10.1`. Previously both `10.0` and `10.1` were used.
> fix: Update terraform-google-project-factory module to 10.1

- 0-bootstrap/README.md
- 1-org/README.md
- 2-environments/README.md
- 3-networks/README.md
- 4-projects/README.md
- test/fixtures/bootstrap/variables.tf
Closes #379 
This PR
- Adds notes in `3-networks` and `4-projects` regarding using same Terraform version for manual steps should be the same one that is used in the Cloud Build, otherwise the user may face a compatibility error if the versions are different.
- Fixes typos.
> Add note regarding terraform version for manual steps

- 0-bootstrap/main.tf
- 0-bootstrap/versions.tf
This PR:
- Removes unused Terraform provider dependencies in `0-bootstrap`. This would close https://github.com/terraform-google-modules/terraform-example-foundation/pull/527, https://github.com/terraform-google-modules/terraform-example-foundation/pull/531 as dependent modules list older versions as constraints.
- Update `terraform-google-modules/bootstrap/google` and `terraform-google-modules/bootstrap/google//modules/cloudbuild` to `3.0`.
> chore(deps): Remove unused dependencies, update bootstrap TF module to 3.0

- 1-org/envs/shared/README.md
- 1-org/envs/shared/iam.tf
- 1-org/envs/shared/variables.tf
Hey folks, 
This pull request comment the code where enable all the audit logs, due to the costs can be generated.
I also added a disclaimer of charges and to remove the comment of the code to enable all of the audit logs.
> fix: data_access_logs_enabled now enables read and write audit logs, defaults to false for cost savings

- 0-bootstrap/main.tf
fixes #644 
This seems to be due to resources like  https://github.com/terraform-google-modules/terraform-google-bootstrap/blob/2f4089fbb8330337b703a5b3037f7b476962911a/main.tf#L177 which are always deployed at org
> fix: always grant view permissions at org to CB SA for TFV

- 1-org/envs/shared/providers.tf
- 2-environments/envs/development/providers.tf
- 2-environments/envs/non-production/providers.tf
- 2-environments/envs/production/providers.tf
- 3-networks/envs/development/providers.tf
- 3-networks/envs/non-production/providers.tf
- 3-networks/envs/production/providers.tf
- 3-networks/envs/shared/providers.tf
- 4-projects/business_unit_1/development/providers.tf
- 4-projects/business_unit_1/non-production/providers.tf
- 4-projects/business_unit_1/production/providers.tf
- 4-projects/business_unit_1/shared/providers.tf
- 4-projects/business_unit_2/development/providers.tf
- 4-projects/business_unit_2/non-production/providers.tf
- 4-projects/business_unit_2/production/providers.tf
- 4-projects/business_unit_2/shared/providers.tf
Hey folks,
This PR fixes issue #281 
Thanks!
> Removes token usage to native impersonation

- build/int.cloudbuild.yaml
This PR fix the error happening in the integration tests:
```
Error: error creating project t01-bu1-d-sample-peering-e2bb (t01-bu1-d-sample-peering): googleapi: Error 409: Requested entity already exists, alreadyExists. If you received a 403 error, make sure you have the `roles/resourcemanager.projectCreator` permission
```
> Changes test prefix project for integration test

- 4-projects/modules/infra_pipelines/cloudbuild_builder/Dockerfile
Add in the docker file a command to guarantee that the execute permission in the entrypoint.bash file is given even in a windows platform.
> feat: add a chmod command to guarantee_execution_permission in the entrypoint.bash file

- 0-bootstrap/versions.tf
- 4-projects/modules/infra_pipelines/versions.tf
> fix: exclude version `4.31.0` from the possible versions for infra pipeline module

- 1-org/README.md
Removed mention to Security Admin Group that does not exist in the documentation.
> Review 1-org README - Security Admin Group

- 1-org/envs/shared/README.md
- 1-org/envs/shared/log_sinks.tf
- 1-org/envs/shared/variables.tf
Creates billing dataset in the multi-regional mode as it's a [requirement](https://cloud.google.com/billing/docs/how-to/export-data-bigquery#:~:text=When%20exporting%20detailed%20usage%20cost%20data%2C%20you,to%20the%20appropriate%20tables%20within%20that%20dataset.) to be able to export billing data.
Users realize the multi-regional dataset limitation post running into an error, and this addressed the need for recreating the dataset.
> create billing dataset in multi-regional by default

- 1-org/README.md
- 3-networks-dual-svpc/README.md
- 3-networks-hub-and-spoke/README.md
- 4-projects/README.md
- 5-app-infra/README.md
Fix directory names on steps that was mentioning `gcp-environments`.
> Fix directory names on steps on READMEs

- 0-bootstrap/README.md
- scripts/validate-requirements.sh
Change gcloud min version to 393.0.0 fix terraform vet error.
Version 393.0.0 is recommended due to terraform-tools 0.5.0 version that fixes the issue mentioned in this [PR 729](https://github.com/terraform-google-modules/terraform-example-foundation/pull/729#discussion_r919427668).
> Change gcloud min version to 393.0.0 to fix terraform vet error

- 1-org/envs/shared/terraform.example.tfvars
Remove undeclared variables:
- `group_org_admins`
- `group_billing_admins`
from step 1-org `terraform.example.tfvars` files
These values are read from the remote state of step 0-bootstrap
> Remove undeclared variables from the terraform.example.tfvars files from step 1-org

- test/integration/bootstrap/bootstrap_test.go
- test/integration/envs/envs_test.go
- test/integration/networks/networks_test.go
- test/integration/org/org_test.go
- test/integration/projects-shared/projects_shared_test.go
- test/integration/projects/projects_test.go
- test/integration/shared/shared_test.go
- test/integration/testutils/retry.go
Retry once on possible transient errors:
- Rate limit exceeded
- Failed to delete non empty folder
- Permission denied on resource
> Retry on transient errors

- 1-org/envs/shared/terraform.example.tfvars
Added `create_unique_tag_key` in terraform.example.tfvars as a suggestion for users to consider this variable when deploying to a folder because tag keys are unique across the organization.
> Add Create Unique Tag Key in terraform.example.tfvars

- 2-environments/modules/env_baseline/folders.tf
- 2-environments/modules/env_baseline/monitoring.tf
- 2-environments/modules/env_baseline/networking.tf
- 2-environments/modules/env_baseline/secrets.tf
- Increased time_sleep to delete env folder to 60 seconds
- Added tags and secrets to wait for the time_sleep
> Fix propagation issues during integrated tests when deleting env folders

- build/cloudbuild-tf-apply.yaml
- build/cloudbuild-tf-plan.yaml
There are now different tokens to be used to do the replacement of the backend bucket name in each step.
Steps 1, 2 and 3 use `UPDATE_ME`
Step 4 uses `UPDATE_PROJECTS_BACKEND`
Step 5 uses `UPDATE_APP_INFRA_BUCKET`
They need to be different  because we are replacing all the backends for steps 1, 2 ,3 and 4 at the end of step 0-bootstrap. for this reason, we now need different token for different values to avoid wrong replacement of the tokens
This PR fixes the regex used in the cloud build files for the regex to be able to work in all the three cases.
> fix sed regex for backend bucket name substitution

- 2-environments/README.md
- 3-networks-dual-svpc/README.md
- 3-networks-hub-and-spoke/README.md
- 4-projects/README.md
- 5-app-infra/README.md
Fix the relative path used in the `-chdir` param of `terraforrm state` command to assume that the user is executing commands at the same level of the `terraform-example-foundation` directory before cloning the Google Cloud Source Repositories.
> fix the relative path used in the chdir param of terraforrm state command

- 3-networks-dual-svpc/README.md
- 3-networks-hub-and-spoke/README.md
- 4-projects/README.md
Unset the GOOGLE_IMPERSONATE_SERVICE_ACCOUNT environment variable used to impersonate the terraform service account when manually  executing Terraform for steps:
- 3-networks-dual-svpc
- 3-networks-hub-and-spoke
-  4-projects
> unset GOOGLE_IMPERSONATE_SERVICE_ACCOUNT after terraform manual execution

- 0-bootstrap/README.md
- 0-bootstrap/cb.tf
- 0-bootstrap/jenkins.tf.example
- 0-bootstrap/main.tf
- 0-bootstrap/outputs.tf
- 0-bootstrap/sa.tf
- 1-org/README.md
- test/integration/bootstrap/bootstrap_test.go
Fixes #865 
Create a workspace for the 0-bootstrap step with:
- custom service account
- roles granted at org level, parent level, and at project level 
- plan trigger
- apply trigger
- gcp-policies repo instructions moved to 0-bootstrap README
Additional change: creation of a state bucket for step 4-projects in the Seed project
> Create a workspace for 0-bootstrap

- 4-projects/README.md
- 5-app-infra/README.md
4-projects/README.md
remote_state_bucket variable should be lowercase.
5-app-infra/README.md
Remove additional closing curly bracket typo
> chore: fix script typos on readmes

- 1-org/README.md
- 2-environments/README.md
- 3-networks-dual-svpc/README.md
- 3-networks-hub-and-spoke/README.md
- 4-projects/README.md
- 5-app-infra/README.md
Fix the link in the README instructions to the  cloud build page in the console to include the region
> fix link to cloud build page in the console

- 0-bootstrap/README-Jenkins.md
- 0-bootstrap/README.md
- 0-bootstrap/scripts/push-to-repo.sh
- 1-org/README.md
- 2-environments/README.md
- 3-networks-dual-svpc/README.md
- 3-networks-hub-and-spoke/README.md
- 4-projects/README.md
- 5-app-infra/README.md
Update default message for initialization of git repositories
> chore: Update default message for initialization of git repositories

- 3-networks-hub-and-spoke/modules/transitivity/main.tf
Enable firewall logging for health check firewall rule in the transitivity configuration for the hub and spoke network mode
> enable firewall logging for health check firewall rule

- 4-projects/modules/single_project/main.tf
Fix source repos to allow user to create as many applications workspaces as user needs and just provide the roles (sa_roles) to user applications.
Previous to this fix user will need to provide each repo key for all applications in sa_roles map.
> Fix source repos keys in sa_roles map

- 0-bootstrap/README-Jenkins.md
- 0-bootstrap/README.md
- 1-org/README.md
Reviewed some deployment steps from CloudBuild that were missing in Jenkins and Terraform local deployment.
> Sync CloudBuild deployment steps with Jenkins and Terraform local steps

- 0-bootstrap/cb.tf
update cloud build private pool peering network CIDR range to use an unused base range instead of a restricted one
> fix: update cloud build private pool peering network CIDR range

- .github/conventional-commit-lint.yaml
The conventional-commit-lint.yaml file is missing the default header
```
Checking file headers
./.github/conventional-commit-lint.yaml
```
> fix: conventional-commit-lint.yaml file must have the default header

- 3-networks-dual-svpc/envs/shared/dns-hub.tf
- 3-networks-dual-svpc/envs/shared/interconnect.tf.example
- 3-networks-dual-svpc/envs/shared/main.tf
- 3-networks-dual-svpc/envs/shared/partner_interconnect.tf.example
- 3-networks-dual-svpc/modules/base_env/interconnect.tf.example
- 3-networks-dual-svpc/modules/base_env/partner_interconnect.tf.example
- 3-networks-dual-svpc/modules/dedicated_interconnect/README.md
- 3-networks-dual-svpc/modules/dedicated_interconnect/main.tf
- 3-networks-dual-svpc/modules/dedicated_interconnect/variables.tf
- 3-networks-dual-svpc/modules/partner_interconnect/README.md
- 3-networks-dual-svpc/modules/partner_interconnect/main.tf
- 3-networks-dual-svpc/modules/partner_interconnect/variables.tf
- 3-networks-hub-and-spoke/envs/shared/interconnect.tf.example
- 3-networks-hub-and-spoke/envs/shared/partner_interconnect.tf.example
- 3-networks-hub-and-spoke/modules/base_env/interconnect.tf.example
- 3-networks-hub-and-spoke/modules/base_env/partner_interconnect.tf.example
- 3-networks-hub-and-spoke/modules/base_shared_vpc/README.md
- 3-networks-hub-and-spoke/modules/base_shared_vpc/outputs.tf
- 3-networks-hub-and-spoke/modules/dedicated_interconnect/README.md
- 3-networks-hub-and-spoke/modules/dedicated_interconnect/main.tf
- 3-networks-hub-and-spoke/modules/dedicated_interconnect/variables.tf
- 3-networks-hub-and-spoke/modules/partner_interconnect/README.md
- 3-networks-hub-and-spoke/modules/partner_interconnect/main.tf
- 3-networks-hub-and-spoke/modules/partner_interconnect/variables.tf
- 3-networks-hub-and-spoke/modules/restricted_shared_vpc/README.md
- 3-networks-hub-and-spoke/modules/restricted_shared_vpc/outputs.tf
Add `onprem_dc` variable for dedicated and partner interconnect and add missing routers outputs in hub and spoke base and restricted modules
> fix: add onprem_dc variable and add missing routers in hub and spoke base and restricted modules

- test/integration/testutils/gcp.go
Golang `testing` library `TB` interface has a private method in its [implementation](https://cs.opensource.google/go/go/+/master:src/testing/testing.go;l=902) to prevent users implementing the interface.
the call to `gcloud.Runf` in the code works because `Runf` uses `go-testing-interface` internally so the `testing` satisfices the requirements for the `go-testing-interface.TB` interface but not the other way around.
When calling the helper from the integration test it works because it is  `testing` => `testing` => `go-testing-interface`  but calling it from the deployer helper we get `go-testing-interface`  => `testing` => `go-testing-interface` with fails.
this change will make the calls be 
- **Integration test:** `testing` => `go-testing-interface` => `go-testing-interface`  
- …
> fix: test helper should import `go-testing-interface` instead of `testing`

- 3-networks-dual-svpc/modules/base_shared_vpc/firewall.tf
- 3-networks-dual-svpc/modules/restricted_shared_vpc/firewall.tf
- 3-networks-hub-and-spoke/modules/base_shared_vpc/firewall.tf
- 3-networks-hub-and-spoke/modules/restricted_shared_vpc/firewall.tf
- 4-projects/modules/base_env/example_peering_project.tf
- test/integration/networks/networks_test.go
This pull request changes the priority of the 'allow-google-apis' firewall rules to prevent collision with the deny all rule. 
See [priority order for firewall rules](https://cloud.google.com/firewall/docs/firewalls#priority_order_for_firewall_rules)
> A rule with a deny action overrides another with an allow action only if the two rules have the same priority.
> fix: change priority of 'allow-google-apis' firewall rules to prevent collision with the deny all rule

- test/integration/app-infra/app_infra_test.go
This PR removes the `DefaultVerify` call from the verify step in the `app-infra` test due to inconsistent return of the tags field in the provider.
> chore: remove DefaultVerify call from the verify in app-infra test due to inconsistent return of the tags field in the provider

- 0-bootstrap/main.tf
- helpers/foundation-deployer/README.md
- helpers/foundation-deployer/global.tfvars.example
- helpers/foundation-deployer/go.mod
- helpers/foundation-deployer/go.sum
- helpers/foundation-deployer/main.go
- helpers/foundation-deployer/msg/msg.go
- helpers/foundation-deployer/stages/apply.go
- helpers/foundation-deployer/stages/data.go
- helpers/foundation-deployer/stages/destroy.go
- helpers/foundation-deployer/stages/validate.go
- helpers/foundation-deployer/stages/vet.go
- helpers/foundation-deployer/steps/steps.go
This PR adds apply/destroy actions for all stages for the foundation deploy helper
> chore: add apply/destroy actions for all stages for the foundation deploy helper

- 1-org/envs/shared/versions.tf
- 1-org/modules/centralized-logging/versions.tf
- 2-environments/modules/env_baseline/versions.tf
- 4-projects/modules/base_env/versions.tf
- 4-projects/modules/single_project/versions.tf
Follow-up to https://github.com/terraform-google-modules/terraform-example-foundation/pull/831
> fix: correct terraform required_version for optional

- .github/workflows/lint.yaml
We don't need swapper anyway since this is not a published module. I will look into either relaxing swapper constraints to exit without err or add a flag for these kind of repos. cc @daniel-cit @apeabody
> chore: fix broken lint

- 0-bootstrap/cb.tf
This PR sets the build timeout for the build that creates the Terraform and gcloud image to 20 minutes.
> fix: set the build timeout for the build that creates the Terraform and gcloud image to 20 minutes

- go.work
- helpers/foundation-deployer/README.md
- helpers/foundation-deployer/go.mod
- test/integration/go.mod
Address security issue raised by codeQL, "invalid Go toolchain version".
>As of Go 1.21, toolchain versions [must use the 1.N.P syntax](https://go.dev/doc/toolchain#version).
1.21 in test/integration/go.mod does not match this syntax and there is no additional toolchain directive, which may cause some go commands to fail.
> chore(golang): invalid Go toolchain version

- 2-environments/envs/nonproduction/terraform.tfvars
- 4-projects/business_unit_1/nonproduction/nonproduction.auto.tfvars
- 4-projects/business_unit_2/nonproduction/nonproduction.auto.tfvars
Fix broken symlinks. Instructions on github are to replace all *.example.tfvars with *.tfvars. Most symlinks for tfvars correctly point to a the *.tfvars files, so that a user following the instructions as written does not need to modify any symlinks.
A small number of files have symlinks to point to *.example.tfvars, which causes deployment errors related to undefined variables and requires troubleshooting to identify and fix. I've corrected these broken symlinks.
> chore(tfvars): fix broken symlinks

- test/integration/testutils/retry.go
- seen in both converge-bootstrap and converge-org steps
> chore(CI): retry Compute Engine API not (yet) enabled

- .github/workflows/go-lint.yaml
- .github/workflows/go-test.yaml
- It seems reasonable to add a dedicated go-test workflow, and exclude helpers/foundation-deployer from the Integration tests
> chore(CI): add go-test for helpers/foundation-deployer

- README.md
The readme segment 5. app-infra has a duplicate `fldr-development-bu2` folder in the output project tree
> fix: removed duplicate folder in README segment 5. app-infra

- 0-bootstrap/github.tf.example
- 0-bootstrap/gitlab.tf.example
- 0-bootstrap/modules/jenkins-agent/main.tf
- 0-bootstrap/modules/tfc-agent-gke/main.tf
- 0-bootstrap/sa.tf
- 0-bootstrap/terraform_cloud.tf.example
- 1-org/modules/cai-monitoring/iam.tf
- 5-app-infra/modules/env_base/main.tf
- test/setup/iam.tf
This PR updates the `project-factory` version in CI/CD projects and also adds the `create_ignore_already_exists` flag to the service accounts created in the foundation.
Fixes #1254
> fix: update project-factory version in CI/CD projects

- 0-bootstrap/Dockerfile
- 0-bootstrap/README-GitHub.md
- 0-bootstrap/README-GitLab.md
- 0-bootstrap/README-Jenkins.md
- 0-bootstrap/README-Terraform-Cloud.md
- 0-bootstrap/README.md
- 0-bootstrap/cb.tf
- 0-bootstrap/modules/jenkins-agent/README.md
- 0-bootstrap/modules/jenkins-agent/variables.tf
- 3-networks-dual-svpc/README.md
- 3-networks-hub-and-spoke/README.md
- 4-projects/README.md
- build/github-tf-apply.yaml
- build/github-tf-pull-request.yaml
- docs/TROUBLESHOOTING.md
- helpers/foundation-deployer/README.md
- scripts/validate-requirements.sh
Bump Terrafom version from [1.3.10](https://github.com/hashicorp/terraform/tree/v1.3.10) to [1.5.7](https://github.com/hashicorp/terraform/tree/v1.5.7)
Version 1.5.7 is the last version before the License change from [Mozilla Public License, version 2.0](https://github.com/hashicorp/terraform/blob/v1.5.7/LICENSE) to [Business Source License 1.1](https://github.com/hashicorp/terraform/blob/main/LICENSE)
> fix: bump terraform version from 1.3.10 to 1.5.7 

- 0-bootstrap/main.tf
> fix: module seed_bootstrap now waiting on module required_groups

- 3-networks-dual-svpc/README.md
I believe this was accidentally changed in when updating README here: https://github.com/terraform-google-modules/terraform-example-foundation/pull/1210/files#diff-103694d8c8f2d87c3ec2f998d3bee4062552b630380365062470339c52531465L61
> fix(docs): Update 3-networks-dual-svpc README after accidental change

- 1-org/modules/cai-monitoring/main.tf
- 1-org/modules/cai-monitoring/versions.tf
This PR bumps the version of the terraform provider on cai-monitoring module to `">= 5.42"` to fix #1306
Terraform provider `5.42.0` [release notes](https://github.com/hashicorp/terraform-provider-google/releases/tag/v5.42.0)
> fix: bump version of terraform provider on cai-monitoring module

- docs/TROUBLESHOOTING.md
Hey folks, this PR contains the addition of instructions for the "project does not exist" error in the TROUBLESHOOTING document, regarding the issue [(1195)](https://github.com/terraform-google-modules/terraform-example-foundation/issues/1195)
> Chore: add "project does not exist" instrunctions on troubleshooting doc

- 1-org/modules/cai-monitoring/main.tf
- 4-projects/modules/base_env/example_storage_cmek.tf
Hey folks, this PR contains changes to the structure of bucket names, so that when the deployment is made in a region with a long name, such as "northamerica-northeast1", the bucket does not exceed the 63 character limit, regarding the issue [(1166)](https://github.com/terraform-google-modules/terraform-example-foundation/issues/1166)
> Fix: bucket name length exceeds 63 characters with non-US region deployment

- helpers/foundation-deployer/README.md
- helpers/foundation-deployer/global.tfvars.example
- helpers/foundation-deployer/stages/apply.go
- helpers/foundation-deployer/stages/data.go
This PR fixes the two location variables (KMS and GCS) for step 4-projects in the deploy helper.
Instructions about enablement of the Security Command Center  to the Helper README were also added.
> fix: fix location variables for step 4-projects in deploy helper

- 3-networks-dual-svpc/modules/hierarchical_firewall_policy/main.tf
- 3-networks-dual-svpc/modules/hierarchical_firewall_policy/outputs.tf
- 3-networks-dual-svpc/modules/hierarchical_firewall_policy/versions.tf
- 3-networks-hub-and-spoke/modules/hierarchical_firewall_policy/main.tf
- 3-networks-hub-and-spoke/modules/hierarchical_firewall_policy/outputs.tf
- 3-networks-hub-and-spoke/modules/hierarchical_firewall_policy/versions.tf
- test/integration/org/org_test.go
The API resources used by `3-networks-dual-svpc/modules/hierarchical_firewall_policy` and `3-networks-hub-and-spoke/modules/hierarchical_firewall_policy` are deprecated and causing deployment failures on Foundation. This pull request addresses the issue by updating the resources to their latest versions.
Issue related: <https://github.com/hashicorp/terraform-provider-google/issues/20657>
> fix!: Fix for hierarchical firewall policy

- 0-bootstrap/README.md
- 0-bootstrap/github.tf.example
- 0-bootstrap/variables.tf
This PR fix unsupported argument for `folder_deletion_protection` and fixes `attribute_condition` value in `gh_oidc` module.
> Fix: Fixes for Github deploy

- 1-org/modules/centralized-logging/main.tf
- 1-org/modules/centralized-logging/versions.tf
This PR fixes the error below that occurs during the destroy-org step, causing the build to fail.
```
Step #33 - "destroy-org":             Error:          Received unexpected error:
Step #33 - "destroy-org":                             FatalError{Underlying: error while running command: exit status 1; 
Step #33 - "destroy-org":                             Error: unable to make request: request failed, retries exceeded: %!s(<nil>)
Step #33 - "destroy-org":                             }
Step #33 - "destroy-org":             Test:           TestOrg
Step #33 - "destroy-org": --- FAIL: TestOrg (150.66s)
Step #33 - "destroy-org": FAIL
Step #33 - "destroy-org": FAIL    github.com/terraform-google-modules/terraform-example-foundation/test/integration/org    150.716s
```
> fix: Retries exceeded in 1-org destroy step

- 0-bootstrap/README-GitHub.md
- 0-bootstrap/README-GitLab.md
- 0-bootstrap/README-Terraform-Cloud.md
This PR is a follow-up fixing procedures.
after https://github.com/terraform-google-modules/terraform-example-foundation/pull/1365 was merged, the branch deployment order for 3-networks-dual-svpc went from 'development -> nonproduction -> production' to 'production -> development -> nonproduction' and this change was missing in other deployment types docs (github, gitlab...)
> fix(docs): update procedures deployment order after DNS refactoring
